### ISSUE TITLE
gCons

### ISSUE THREAD

**Issue by sergeyklay** [gleez/cms#44]
## gCons for my theme

I created the gCons sprite image from [Comprehensive collection of 100 creative, open source and multi-purpose icons **in 2** colors for the web and desktop applications)](http://www.greepit.com/open-source-icons-gcons/)

**CSS may be so:**

``` css
[class^="gcon-"],[class*=" gcon-"]{display:inline-block;width:32px;height:32px;*margin-right:.3em;line-height:32px;vertical-align:top;background-image:url("../img/gcons-grey.png");background-position:32px 32px;background-repeat:no-repeat;margin-top:1px}
.nav li>a:hover>[class^="gcon-"],.nav li>a:hover>[class*=" gcon-"]{background-image:url("../img/gcons-grey-inverse.png")}
.icon-grey-inverse{background-image:url("../img/gcons-grey-inverse.png")}
.nav li>a:hover>.icon-grey-inverse{background-image:url("../img/gcons-grey.png")}
.gcon-add-item{background-position: 0 0}
.gcon-addressbook{background-position: -32px  0}
.gcon-agent{background-position: -64px 0}
.gcon-apple{background-position: -96px 0}
.gcon-arrow-round{background-position: -128px 0}
.gcon-badge{background-position: -160px 0}
.gcon-bar-chart1{background-position: -192px 0}
.gcon-bar-chart2{background-position: -224px 0}
.gcon-battery-full{background-position: -256px 0}
.gcon-bird{background-position: -288px 0}
.gcon-boat{background-position: -320px 0}
.gcon-bookmark{background-position: -352px 0}
.gcon-briefcase{background-position: -384px 0}
.gcon-calculator{background-position: -416px 0}
.gcon-calendar{background-position: -448px 0}
.gcon-cassette{background-position: -480px 0}
.gcon-chain{background-position: -512px 0}
.gcon-chat1{background-position: -544px 0}
.gcon-chat2{background-position: -576px 0}
.gcon-cloud-filled{background-position: -608px 0}
.gcon-cloud-outline{background-position: 0 -32px}
.gcon-computer{background-position: -32px -32px}
.gcon-configuration1{background-position: -64px -32px}
.gcon-configuration2{background-position: -96px -32px}
.gcon-connected{background-position: -128px -32px}
.gcon-connections{background-position: -160px -32px}
.gcon-container{background-position: -192px -32px}
.gcon-copy-item{background-position: -224px -32px}
.gcon-database{background-position: -256px -32px}
.gcon-delete-item{background-position: -288px -32px}
.gcon-disc{background-position: -320px -32px}
.gcon-dollar{background-position: -352px -32px}
.gcon-download{background-position: -384px -32px}
.gcon-edit{background-position: -416px -32px}
.gcon-email{background-position: -448px -32px}
.gcon-fan{background-position: -480px -32px}
.gcon-fancy-globe{background-position: -512px -32px}
.gcon-female-user{background-position: -544px -32px}
.gcon-fire{background-position: -576px -32px}
.gcon-first-aid{background-position: -608px -32px}
.gcon-flag{background-position: 0 -64px}
.gcon-flower{background-position: -32px -64px}
.gcon-full-screen{background-position: -64px -64px}
.gcon-glasses{background-position: -96px -64px}
.gcon-globe{background-position: -128px -64px}
.gcon-happy-face{background-position: -160px -64px}
.gcon-headphone{background-position: -192px -64px}
.gcon-heart{background-position: -224px -64px}
.gcon-home{background-position: -256px -64px}
.gcon-id{background-position: -288px -64px}
.gcon-ipod{background-position: -320px -64px}
.gcon-lab{background-position: -352px -64px}
.gcon-lady{background-position: -384px -64px}
.gcon-lamp{background-position: -416px -64px}
.gcon-leaves{background-position: -448px -64px}
.gcon-light{background-position: -480px -64px}
.gcon-line-globe{background-position: -512px -64px}
.gcon-lock{background-position: -544px -64px}
.gcon-lookup{background-position: -576px -64px}
.gcon-male-user{background-position: -608px -64px}
.gcon-microphone{background-position: 0 -96px}
.gcon-mobile1{background-position: -32px -96px}
.gcon-mobile2{background-position: -64px -96px}
.gcon-mouse{background-position: -96px -96px}
.gcon-multi-agents{background-position: -128px -96px}
.gcon-music-node{background-position: -160px -96px}
.gcon-network{background-position: -192px -96px}
.gcon-network-pc{background-position: -224px -96px}
.gcon-next-item{background-position: -256px -96px}
.gcon-phone{background-position: -288px -96px}
.gcon-pie-chart{background-position: -320px -96px}
.gcon-pin{background-position: -352px -96px}
.gcon-plane{background-position: -384px -96px}
.gcon-print{background-position: -416px -96px}
.gcon-processing1{background-position: -448px -96px}
.gcon-processing2{background-position: -480px -96px}
.gcon-push-pin{background-position: -512px -96px}
.gcon-recycle-empty{background-position: -544px -96px}
.gcon-recycle-full{background-position: -576px -96px}
.gcon-reload{background-position: -608px -96px}
.gcon-rss{background-position: 0 -128px}
.gcon-satellite{background-position: -32px -128px}
.gcon-save{background-position: -64px -128px}
.gcon-scale{background-position: -96px -128px}
.gcon-scissors{background-position: -128px -128px}
.gcon-screen{background-position: -160px -128px}
.gcon-search{background-position: -192px -128px}
.gcon-server{background-position: -224px -128px}
.gcon-shield{background-position: -256px -128px}
.gcon-shut-down{background-position: -288px -128px}
.gcon-star{background-position: -320px -128px}
.gcon-tag{background-position: -352px -128px}
.gcon-tap{background-position: -384px -128px}
.gcon-tree{background-position: -416px -128px}
.gcon-umbrella{background-position: -448px -128px}
.gcon-unlock{background-position: -480px -128px}
.gcon-usb{background-position: -512px -128px}
.gcon-van{background-position: -544px -128px}
.gcon-wifi{background-position: -576px -128px}
.gcon-world{background-position: -608px -128px}
```

**HTML may be so:**

``` html
    <div id="photo" class="well">
      <ul class="nav nav-list">
        <li><a href="#"><i class="gcon-id icon-grey-inverse"></i> Change photo</a></li>
        <li><a href="#"><i class="gcon-agent icon-grey-inverse"></i> Modify profile</a></li>
        <li><a href="#"><i class="gcon-server icon-grey-inverse"></i> Change password</a></li>
      </ul>
    </div>
```

Icons are here: http://klay.me/i/icons/gcons/
Screenshot: see atachment
Sizes: http://vpaste.net/IDSO5

I would be happy if you come in handy

![using-gcons-example](https://f.cloud.github.com/assets/1256298/37972/dc7a439e-54c0-11e2-894a-1f3cdfff13a7.png)
