### ISSUE TITLE
Font-size in Datatables for BS3

### ISSUE THREAD

**Issue by sergeyklay** [gleez/cms#608]
@sandeepone Please see screenshot. It seems image corrupted 

![datatable](https://f.cloud.github.com/assets/1256298/1573080/16cd09d0-512a-11e3-84cf-2a3fc26981f4.PNG)

Font size 12px is small ( `greet.dataTables.css` )

``` css
    table.dataTable tr {
    font-size: 12px;
    line-height: 24px;
}
```
